### ISSUE TITLE
Ruby Group Capstone Project

### ISSUE THREAD

**Issue by ZahraArshia** [bushmusi/my-catalog#39]
Hello 😊 
[project kanban link](https://github.com/bushmusi/my-catalog/projects/2)
**The members of the group:**
- Member 1: implementation of book related classes and methods @bushmusi 
- Member 2: implementation of music related classes and methods @usorfaitheloho 
- Member 3: implementation of game related classes and methods @ZahraArshia

**Comment by elyor-doniyorov** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔️ You have sent a link to the GitHub issue that has a link to the GitHub project
✔️ All cards are assigned to team members

## Required Changes ♻️
- [ ] Please make sure that each card on the board has a description of the task. Right now some of your tasks do not have them.
- [ ] Some of @usorfaitheloho tasks do not have points. Kindly give points for each task. Also, make sure that you do not have significantly (difference >= 5 points) more or less points than others. Please, fix it and ask again for a review.

_Do not check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bushmusi** [comment]
> Hi Team,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> ✔️ You have sent a link to the GitHub issue that has a link to the GitHub project ✔️ All cards are assigned to team members
> 
> ## Required Changes ♻️
> * [ ]  Please make sure that each card on the board has a description of the task. Right now some of your tasks do not have them.
> * [ ]  Some of @usorfaitheloho tasks do not have points. Kindly give points for each task. Also, make sure that you do not have significantly (difference >= 5 points) more or less points than others. Please, fix it and ask again for a review.
> 
> _Do not check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
> * N/A
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks for the constructive feedback, Fixed now

**Comment by Lordkaito** [comment]
Hi team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] Just as the previous reviewer mentioned, please make sure to include a description of all your issue. I am not sure if you submitted the wrong link for re-review or just forgot to apply this change, because right now I can see that there are still some issues with no description, so please make sure to fix this issue.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by usorfaitheloho** [comment]
Hello 😊

This is our project kanban board
[project kanban link](https://github.com/bushmusi/my-catalog/projects/2)
The members of the group are:

Member 1: implementation of book related classes and methods @bushmusi
Member 2: implementation of music related classes and methods @usorfaitheloho
Member 3: implementation of game related classes and methods @ZahraArshia

**Comment by Mihndim2020** [comment]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi Team, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
